[package]
name = "mimirsbrunn"
version = "1.16.0"
authors = ["Canal TP <dt.ro@canaltp.fr>"]
build = "build.rs"
autotests = false
edition = "2018"

[workspace]

[features]
default = [ "db-storage" ]
db-storage = [ "rusqlite" ]

[dependencies]
log = { version = "0.4", features = ["release_max_level_debug"] }
slog = { version = "2.5", features = ["max_level_trace", "release_max_level_debug"]}
slog-scope = "4.3"
slog-envlogger = "2.2"
slog-async = "2.5"
structopt = "0.3"
csv = "1.1"
rs-es = { git = "https://github.com/canaltp/rs-es", features = ["geo"]}
regex = "1"
osmpbfreader = "0.13"
osm_boundaries_utils = "0.6"
chrono = "0.4"
serde = {version = "1", features = ["rc"]}
serde_json = "1"
bincode = "1.2"
geo = "0.15"
geo-types = { version = "0.6.1", features = [ "rstar" ] }
rstar = "0.8"
itertools = "0.9"
transit_model = "0.20"
typed_index_collection = "1.1"
failure = "0.1"
cosmogony = "0.8.1"
par-map = "0.1.4"
lazy_static = "1.4"
num_cpus = "1.13"
assert_float_eq = "1.1"
human-sort = "0.2"
address-formatter = "0.2.1"
navitia-poi-model = "0.3"
walkdir = "2.3"
rusqlite = { version = "0.23", optional = true }
flate2 = "1.0"
rayon = "1.0"

mimir = { path = "libs/mimir" }
bragi = { path = "libs/bragi" }

[dev-dependencies]
reqwest = { version = "0.10", features = [ "blocking", "json" ] }
approx = "0.3"
actix-web = "1"
tools = { path = "libs/tools" }
docker_wrapper = { path = "libs/docker_wrapper" }

[build-dependencies]
json = "0.12"

# we just call one test method: cf. tests::all_tests()
[[test]]
name = "tests"
