[package]
name = "mimirsbrunn"
version = "1.15.0"
authors = ["Canal TP <dt.ro@canaltp.fr>"]
build = "build.rs"
autotests = false
edition = "2018"

[workspace]

[dependencies]
log = { version = "0.4", features = ["release_max_level_debug"] }
slog = { version = "2.4", features = ["max_level_trace", "release_max_level_debug"]}
slog-scope = "4.1"
slog-envlogger = "2.1"
slog-async = "2.3"
structopt = "0.3"
csv = "1"
rs-es = { git = "https://github.com/canaltp/rs-es", features = ["geo"]}
regex = "1"
osmpbfreader = "0.13.2"
chrono = "0.4"
serde = {version = "1", features = ["rc"]}
serde_json = "1"
bincode = "1.1"
geo = "0.12.2"
geo-types = { version = "0.4.3", features = [ "rstar" ] }
rstar = "0.7"
itertools = "0.8"
transit_model = "0.8"
transit_model_collection = "*"
osm_boundaries_utils = "0.5"
failure = "0.1"
cosmogony = "0.7"
par-map = "0.1.4"
lazy_static = "1.3"
num_cpus = "1.10"
assert_float_eq = "1"
humanesort = "0.1.0-alpha"
address-formatter = "^0.2.1"
navitia-poi-model = "0.2.1"
walkdir = "2"
rusqlite = "0.20"
flate2 = "1.0"
# quote = "=1.0.1"
actix-rt = "1.1.1"

mimir = { path = "libs/mimir" }
bragi = { path = "libs/bragi" }

[dev-dependencies]
reqwest = "=0.9.16"
approx = "0.3"
actix-web = "1"
tools = { path = "libs/tools" }
docker_wrapper = { path = "libs/docker_wrapper" }

[build-dependencies]
git-version = "0.2"
json = "0.12"

# we just call one test method: cf. tests::all_tests()
[[test]]
name = "tests"
